version: "3.8"

services:
    mysql:
        container_name: compras
        hostname: compras
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: dba
            MYSQL_DATABASE: dba
            MYSQL_USER: dba
            MYSQL_PASSWORD: dba
            MYSQL_INIT_COMMAND: "SET sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
        volumes:
            - .data:/data/src/volumes
        ports:
            - 3306:3306
